name: Trigger build
on:
  push:
    branches: [main]

jobs:
  trigger-bulid:
    name: Trigger container build
    runs-on: ubuntu-latest
    steps:
      - name: Trigger container build
        run: |
          curl -L \
            -v \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.EXPENSES_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/farting-lizards/expenses-container/dispatches \
            -d '{"event_type": "fe-change"}'